<a href="https://colab.research.google.com/github/Muhammad-Farhan-A/Kelompok-2-APM-B/blob/main/Prak3_GaussianNaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
#import library
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [15]:
#import dataset
dataset = pd.read_csv("heart_dataset.csv")
dataset.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [18]:
#analisis dataset
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [19]:
#variabel independen
x = dataset.drop(['target'], axis = 1)
x.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2

In [20]:
#variabel dependen
y = dataset['target']
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [21]:
#split data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 123)

In [22]:
#mengaktifkan package dan fungsi gaussian naive bayes
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [23]:
#memasukkan data training pada fungsi
nb = model.fit(x_train, y_train)

In [24]:
#melakukan prediksi
y_pred = nb.predict(x_test)
y_pred

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 1])

In [25]:
#menentukan probabilitas hasil prediksi
nb.predict_proba(x_test)

array([[2.30496874e-03, 9.97695031e-01],
       [5.77097010e-02, 9.42290299e-01],
       [9.53033517e-01, 4.69664832e-02],
       [3.81502666e-01, 6.18497334e-01],
       [9.96851324e-01, 3.14867605e-03],
       [9.91136141e-01, 8.86385892e-03],
       [8.80478119e-04, 9.99119522e-01],
       [9.99981756e-01, 1.82438100e-05],
       [9.98996897e-01, 1.00310312e-03],
       [9.99966979e-01, 3.30206308e-05],
       [9.29519523e-01, 7.04804773e-02],
       [3.95757075e-03, 9.96042429e-01],
       [9.68272731e-02, 9.03172727e-01],
       [4.35944288e-02, 9.56405571e-01],
       [3.75304412e-01, 6.24695588e-01],
       [9.99467388e-01, 5.32611815e-04],
       [9.44809933e-01, 5.51900675e-02],
       [9.47479912e-01, 5.25200885e-02],
       [9.91136141e-01, 8.86385892e-03],
       [9.96851324e-01, 3.14867605e-03],
       [1.20144184e-01, 8.79855816e-01],
       [1.93039214e-01, 8.06960786e-01],
       [8.57722948e-02, 9.14227705e-01],
       [7.82806546e-02, 9.21719345e-01],
       [9.89337225e-01, 1.06627747e-02],
       [9.93732407e-01, 6.26759289e-03],
       [3.43334222e-01, 6.56665778e-01],
       [2.97178680e-01, 7.02821320e-01],
       [9.69553201e-01, 3.04467988e-02],
       [8.57722948e-02, 9.14227705e-01],
       [9.99999977e-01, 2.32682572e-08],
       [8.80478119e-04, 9.99119522e-01],
       [4.83535485e-01, 5.16464515e-01],
       [9.96649712e-01, 3.35028836e-03],
       [7.79165429e-01, 2.20834571e-01],
       [6.97009208e-01, 3.02990792e-01],
       [1.76924140e-02, 9.82307586e-01],
       [9.99978783e-01, 2.12165991e-05],
       [2.96332878e-03, 9.97036671e-01],
       [9.99827183e-01, 1.72816977e-04],
       [9.99953845e-01, 4.61548868e-05],
       [9.29519523e-01, 7.04804773e-02],
       [9.47729502e-01, 5.22704976e-02],
       [2.89873234e-03, 9.97101268e-01],
       [9.99791501e-01, 2.08498910e-04],
       [9.98774348e-01, 1.22565173e-03],
       [4.73876129e-01, 5.26123871e-01],
       [9.98442566e-01, 1.55743430e-03],
       [3.80665500e-02, 9.61933450e-01],
       [9.42644715e-03, 9.90573553e-01],
       [6.94897340e-04, 9.99305103e-01],
       [3.14925090e-01, 6.85074910e-01],
       [9.67613044e-04, 9.99032387e-01],
       [1.34056042e-03, 9.98659440e-01],
       [9.55019700e-01, 4.49802998e-02],
       [2.30442493e-02, 9.76955751e-01],
       [2.43353766e-03, 9.97566462e-01],
       [8.00784765e-01, 1.99215235e-01],
       [3.75304412e-01, 6.24695588e-01],
       [2.87553000e-01, 7.12447000e-01],
       [2.01081727e-01, 7.98918273e-01],
       [9.99860601e-01, 1.39398808e-04],
       [7.92316133e-01, 2.07683867e-01],
       [8.80478119e-04, 9.99119522e-01],
       [9.47479912e-01, 5.25200885e-02],
       [6.74986322e-04, 9.99325014e-01],
       [3.28828421e-03, 9.96711716e-01],
       [9.30711963e-01, 6.92880374e-02],
       [1.90554816e-01, 8.09445184e-01],
       [7.96313621e-03, 9.92036864e-01],
       [8.04466612e-01, 1.95533388e-01],
       [4.64753122e-04, 9.99535247e-01],
       [4.36542399e-02, 9.56345760e-01],
       [4.64753122e-04, 9.99535247e-01],
       [2.30442493e-02, 9.76955751e-01],
       [4.93140951e-02, 9.50685905e-01],
       [9.94472372e-01, 5.52762756e-03],
       [5.11882896e-04, 9.99488117e-01],
       [9.98774348e-01, 1.22565173e-03],
       [2.86966079e-01, 7.13033921e-01],
       [1.34056042e-03, 9.98659440e-01],
       [2.87553000e-01, 7.12447000e-01],
       [3.24228388e-03, 9.96757716e-01],
       [9.99967024e-01, 3.29763278e-05],
       [9.30711963e-01, 6.92880374e-02],
       [3.81409529e-01, 6.18590471e-01],
       [9.98012750e-01, 1.98725030e-03],
       [7.22631829e-03, 9.92773682e-01],
       [8.68655837e-01, 1.31344163e-01],
       [1.48360271e-03, 9.98516397e-01],
       [3.75304412e-01, 6.24695588e-01],
       [9.21176633e-01, 7.88233675e-02],
       [9.34119802e-02, 9.06588020e-01],
       [9.99986632e-01, 1.33677428e-05],
       [3.29506730e-01, 6.70493270e-01],
       [4.33766828e-01, 5.66233172e-01],
       [9.88447707e-01, 1.15522931e-02],
       [9.33127182e-03, 9.90668728e-01],
       [5.66906294e-03, 9.94330937e-01],
       [9.98017886e-01, 1.98211448e-03],
       [9.94273799e-01, 5.72620104e-03],
       [9.98141961e-01, 1.85803892e-03],
       [9.91344530e-01, 8.65546977e-03],
       [9.99993457e-01, 6.54312453e-06],
       [5.49413515e-03, 9.94505865e-01],
       [8.96882769e-03, 9.91031172e-01],
       [6.22306740e-01, 3.77693260e-01],
       [5.66906294e-03, 9.94330937e-01],
       [9.99467388e-01, 5.32611815e-04],
       [6.65618912e-01, 3.34381088e-01],
       [9.98023946e-01, 1.97605438e-03],
       [3.14925090e-01, 6.85074910e-01],
       [3.27733182e-01, 6.72266818e-01],
       [9.99946288e-01, 5.37116301e-05],
       [9.99948209e-01, 5.17913513e-05],
       [5.02215964e-01, 4.97784036e-01],
       [9.99953845e-01, 4.61548868e-05],
       [2.45636133e-01, 7.54363867e-01],
       [8.68655837e-01, 1.31344163e-01],
       [2.86162825e-01, 7.13837175e-01],
       [4.59669465e-03, 9.95403305e-01],
       [2.25933419e-03, 9.97740666e-01],
       [3.66025505e-01, 6.33974495e-01],
       [3.81502666e-01, 6.18497334e-01],
       [1.23326836e-01, 8.76673164e-01],
       [9.20693717e-01, 7.93062832e-02],
       [9.98141961e-01, 1.85803892e-03],
       [9.99933416e-01, 6.65836100e-05],
       [9.98017886e-01, 1.98211448e-03],
       [2.00252301e-03, 9.97997477e-01],
       [9.99953605e-01, 4.63946002e-05],
       [9.99981756e-01, 1.82438100e-05],
       [6.77618062e-02, 9.32238194e-01],
       [3.27733182e-01, 6.72266818e-01],
       [9.48513663e-01, 5.14863367e-02],
       [3.32438764e-02, 9.66756124e-01],
       [1.53597993e-01, 8.46402007e-01],
       [6.82898555e-01, 3.17101445e-01],
       [5.15791440e-02, 9.48420856e-01],
       [6.80012451e-01, 3.19987549e-01],
       [9.34119802e-02, 9.06588020e-01],
       [4.64753122e-04, 9.99535247e-01],
       [9.70688740e-01, 2.93112599e-02],
       [4.02998942e-02, 9.59700106e-01],
       [7.82806546e-02, 9.21719345e-01],
       [4.35944288e-02, 9.56405571e-01],
       [6.65618912e-01, 3.34381088e-01],
       [9.93211437e-01, 6.78856297e-03],
       [9.75991230e-01, 2.40087702e-02],
       [9.99999977e-01, 2.32682572e-08],
       [9.89837453e-01, 1.01625472e-02],
       [3.76003646e-03, 9.96239964e-01],
       [4.33766828e-01, 5.66233172e-01],
       [2.20175727e-02, 9.77982427e-01],
       [9.38109228e-03, 9.90618908e-01],
       [9.99953845e-01, 4.61548868e-05],
       [9.98224751e-01, 1.77524945e-03],
       [6.05716918e-04, 9.99394283e-01],
       [1.28597879e-03, 9.98714021e-01],
       [2.96332878e-03, 9.97036671e-01],
       [1.60829567e-01, 8.39170433e-01],
       [2.19790505e-02, 9.78020949e-01],
       [6.27184146e-03, 9.93728159e-01],
       [9.99973471e-01, 2.65285946e-05],
       [8.29030637e-02, 9.17096936e-01],
       [1.00000000e+00, 7.92489117e-11],
       [9.98328552e-01, 1.67144803e-03],
       [9.44809933e-01, 5.51900675e-02],
       [9.74071567e-01, 2.59284325e-02],
       [9.98978588e-01, 1.02141235e-03],
       [2.97178680e-01, 7.02821320e-01],
       [7.61156598e-01, 2.38843402e-01],
       [1.90554816e-01, 8.09445184e-01],
       [9.91344530e-01, 8.65546977e-03],
       [3.17543851e-02, 9.68245615e-01],
       [4.36793714e-01, 5.63206286e-01],
       [1.00000000e+00, 7.92489117e-11],
       [9.99467388e-01, 5.32611815e-04],
       [9.88447707e-01, 1.15522931e-02],
       [1.52853165e-02, 9.84714683e-01],
       [4.52725991e-03, 9.95472740e-01],
       [9.98996897e-01, 1.00310312e-03],
       [9.98017886e-01, 1.98211448e-03],
       [9.86146911e-01, 1.38530895e-02],
       [2.25933419e-03, 9.97740666e-01],
       [9.98978588e-01, 1.02141235e-03],
       [4.36542399e-02, 9.56345760e-01],
       [6.97009208e-01, 3.02990792e-01],
       [9.74071567e-01, 2.59284325e-02],
       [7.25064275e-02, 9.27493572e-01],
       [9.99999977e-01, 2.32682572e-08],
       [9.99159355e-01, 8.40645227e-04],
       [9.86146911e-01, 1.38530895e-02],
       [6.80012451e-01, 3.19987549e-01],
       [3.32438764e-02, 9.66756124e-01],
       [9.99984239e-01, 1.57608969e-05],
       [9.99428053e-01, 5.71946904e-04],
       [6.82898555e-01, 3.17101445e-01],
       [9.65633635e-04, 9.99034366e-01],
       [3.32438764e-02, 9.66756124e-01],
       [6.86354802e-04, 9.99313645e-01],
       [3.81502666e-01, 6.18497334e-01],
       [6.77618062e-02, 9.32238194e-01],
       [9.98825641e-01, 1.17435871e-03],
       [6.08471348e-03, 9.93915287e-01]])

In [26]:
#akurasi
print("Gaussian Naive Bayes score: ",nb.score(x_test, y_test))

Gaussian Naive Bayes score:  0.8390243902439024